int imageSize(readonly writeonly volatile coherent image1D image);
int imageSize(readonly writeonly volatile coherent iimage1D image);
int imageSize(readonly writeonly volatile coherent uimage1D image);
ivec2 imageSize(readonly writeonly volatile coherent image2D image);
ivec2 imageSize(readonly writeonly volatile coherent iimage2D image);
ivec2 imageSize(readonly writeonly volatile coherent uimage2D image);
ivec3 imageSize(readonly writeonly volatile coherent image3D image);
ivec3 imageSize(readonly writeonly volatile coherent iimage3D image);
ivec3 imageSize(readonly writeonly volatile coherent uimage3D image);
ivec2 imageSize(readonly writeonly volatile coherent imageCube image);
ivec2 imageSize(readonly writeonly volatile coherent iimageCube image);
ivec2 imageSize(readonly writeonly volatile coherent uimageCube image);
ivec2 imageSize(readonly writeonly volatile coherent image2DRect image);
ivec2 imageSize(readonly writeonly volatile coherent iimage2DRect image);
ivec2 imageSize(readonly writeonly volatile coherent uimage2DRect image);
int imageSize(readonly writeonly volatile coherent imageBuffer image);
int imageSize(readonly writeonly volatile coherent iimageBuffer image);
int imageSize(readonly writeonly volatile coherent uimageBuffer image);
ivec2 imageSize(readonly writeonly volatile coherent image1DArray image);
ivec2 imageSize(readonly writeonly volatile coherent iimage1DArray image);
ivec2 imageSize(readonly writeonly volatile coherent uimage1DArray image);
ivec3 imageSize(readonly writeonly volatile coherent image2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent iimage2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent uimage2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent imageCubeArray image);
ivec3 imageSize(readonly writeonly volatile coherent iimageCubeArray image);
ivec3 imageSize(readonly writeonly volatile coherent uimageCubeArray image);
ivec2 imageSize(readonly writeonly volatile coherent image2DMS image);
ivec2 imageSize(readonly writeonly volatile coherent iimage2DMS image);
ivec2 imageSize(readonly writeonly volatile coherent uimage2DMS image);
ivec3 imageSize(readonly writeonly volatile coherent image2DMSArray image);
ivec3 imageSize(readonly writeonly volatile coherent iimage2DMSArray image);
ivec3 imageSize(readonly writeonly volatile coherent uimage2DMSArray image);
int imageSamples(readonly writeonly volatile coherent image2DMS image);
int imageSamples(readonly writeonly volatile coherent iimage2DMS image);
int imageSamples(readonly writeonly volatile coherent uimage2DMS image);
int imageSamples(readonly writeonly volatile coherent image2DMSArray image);
int imageSamples(readonly writeonly volatile coherent iimage2DMSArray image);
int imageSamples(readonly writeonly volatile coherent uimage2DMSArray image);
vec4 imageLoad(readonly volatile coherent image1D image, int P);
ivec4 imageLoad(readonly volatile coherent iimage1D image, int P);
uvec4 imageLoad(readonly volatile coherent uimage1D image, int P);
vec4 imageLoad(readonly volatile coherent image2D image, ivec2 P);
ivec4 imageLoad(readonly volatile coherent iimage2D image, ivec2 P);
uvec4 imageLoad(readonly volatile coherent uimage2D image, ivec2 P);
vec4 imageLoad(readonly volatile coherent image3D image, ivec3 P);
ivec4 imageLoad(readonly volatile coherent iimage3D image, ivec3 P);
uvec4 imageLoad(readonly volatile coherent uimage3D image, ivec3 P);
vec4 imageLoad(readonly volatile coherent imageCube image, ivec3 P);
ivec4 imageLoad(readonly volatile coherent iimageCube image, ivec3 P);
uvec4 imageLoad(readonly volatile coherent uimageCube image, ivec3 P);
vec4 imageLoad(readonly volatile coherent image2DRect image, ivec2 P);
ivec4 imageLoad(readonly volatile coherent iimage2DRect image, ivec2 P);
uvec4 imageLoad(readonly volatile coherent uimage2DRect image, ivec2 P);
vec4 imageLoad(readonly volatile coherent imageBuffer image, int P);
ivec4 imageLoad(readonly volatile coherent iimageBuffer image, int P);
uvec4 imageLoad(readonly volatile coherent uimageBuffer image, int P);
vec4 imageLoad(readonly volatile coherent image1DArray image, ivec2 P);
ivec4 imageLoad(readonly volatile coherent iimage1DArray image, ivec2 P);
uvec4 imageLoad(readonly volatile coherent uimage1DArray image, ivec2 P);
vec4 imageLoad(readonly volatile coherent image2DArray image, ivec3 P);
ivec4 imageLoad(readonly volatile coherent iimage2DArray image, ivec3 P);
uvec4 imageLoad(readonly volatile coherent uimage2DArray image, ivec3 P);
vec4 imageLoad(readonly volatile coherent imageCubeArray image, ivec3 P);
ivec4 imageLoad(readonly volatile coherent iimageCubeArray image, ivec3 P);
uvec4 imageLoad(readonly volatile coherent uimageCubeArray image, ivec3 P);
vec4 imageLoad(readonly volatile coherent image2DMS image, ivec2 P, int sample);
ivec4 imageLoad(readonly volatile coherent iimage2DMS image, ivec2 P, int sample);
uvec4 imageLoad(readonly volatile coherent uimage2DMS image, ivec2 P, int sample);
vec4 imageLoad(readonly volatile coherent image2DMSArray image, ivec3 P, int sample);
ivec4 imageLoad(readonly volatile coherent iimage2DMSArray image, ivec3 P, int sample);
uvec4 imageLoad(readonly volatile coherent uimage2DMSArray image, ivec3 P, int sample);
void imageStore(writeonly volatile coherent image1D image, int P, vec4 data);
void imageStore(writeonly volatile coherent iimage1D image, int P, ivec4 data);
void imageStore(writeonly volatile coherent uimage1D image, int P, uvec4 data);
void imageStore(writeonly volatile coherent image2D image, ivec2 P, vec4 data);
void imageStore(writeonly volatile coherent iimage2D image, ivec2 P, ivec4 data);
void imageStore(writeonly volatile coherent uimage2D image, ivec2 P, uvec4 data);
void imageStore(writeonly volatile coherent image3D image, ivec3 P, vec4 data);
void imageStore(writeonly volatile coherent iimage3D image, ivec3 P, ivec4 data);
void imageStore(writeonly volatile coherent uimage3D image, ivec3 P, uvec4 data);
void imageStore(writeonly volatile coherent imageCube image, ivec3 P, vec4 data);
void imageStore(writeonly volatile coherent iimageCube image, ivec3 P, ivec4 data);
void imageStore(writeonly volatile coherent uimageCube image, ivec3 P, uvec4 data);
void imageStore(writeonly volatile coherent image2DRect image, ivec2 P, vec4 data);
void imageStore(writeonly volatile coherent iimage2DRect image, ivec2 P, ivec4 data);
void imageStore(writeonly volatile coherent uimage2DRect image, ivec2 P, uvec4 data);
void imageStore(writeonly volatile coherent imageBuffer image, int P, vec4 data);
void imageStore(writeonly volatile coherent iimageBuffer image, int P, ivec4 data);
void imageStore(writeonly volatile coherent uimageBuffer image, int P, uvec4 data);
void imageStore(writeonly volatile coherent image1DArray image, ivec2 P, vec4 data);
void imageStore(writeonly volatile coherent iimage1DArray image, ivec2 P, ivec4 data);
void imageStore(writeonly volatile coherent uimage1DArray image, ivec2 P, uvec4 data);
void imageStore(writeonly volatile coherent image2DArray image, ivec3 P, vec4 data);
void imageStore(writeonly volatile coherent iimage2DArray image, ivec3 P, ivec4 data);
void imageStore(writeonly volatile coherent uimage2DArray image, ivec3 P, uvec4 data);
void imageStore(writeonly volatile coherent imageCubeArray image, ivec3 P, vec4 data);
void imageStore(writeonly volatile coherent iimageCubeArray image, ivec3 P, ivec4 data);
void imageStore(writeonly volatile coherent uimageCubeArray image, ivec3 P, uvec4 data);
void imageStore(writeonly volatile coherent image2DMS image, ivec2 P, int sample, vec4 data);
void imageStore(writeonly volatile coherent iimage2DMS image, ivec2 P, int sample, ivec4 data);
void imageStore(writeonly volatile coherent uimage2DMS image, ivec2 P, int sample, uvec4 data);
void imageStore(writeonly volatile coherent image2DMSArray image, ivec3 P, int sample, vec4 data);
void imageStore(writeonly volatile coherent iimage2DMSArray image, ivec3 P, int sample, ivec4 data);
void imageStore(writeonly volatile coherent uimage2DMSArray image, ivec3 P, int sample, uvec4 data);

__glsld_syscmd_begin_context__;
__glsld_syscmd_require_extension__ GL_EXT_shader_explicit_arithmetic_types_int64;

int imageSize(readonly writeonly volatile coherent i64image1D image);
ivec2 imageSize(readonly writeonly volatile coherent i64image2D image);
ivec3 imageSize(readonly writeonly volatile coherent i64image3D image);
ivec2 imageSize(readonly writeonly volatile coherent i64imageCube image);
ivec2 imageSize(readonly writeonly volatile coherent i64image2DRect image);
int imageSize(readonly writeonly volatile coherent i64imageBuffer image);
ivec2 imageSize(readonly writeonly volatile coherent i64image1DArray image);
ivec3 imageSize(readonly writeonly volatile coherent i64image2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent i64imageCubeArray image);
ivec2 imageSize(readonly writeonly volatile coherent i64image2DMS image);
ivec3 imageSize(readonly writeonly volatile coherent i64image2DMSArray image);
int imageSamples(readonly writeonly volatile coherent i64image2DMS image);
int imageSamples(readonly writeonly volatile coherent i64image2DMSArray image);
i64vec4 imageLoad(readonly volatile coherent i64image1D image, int P);
i64vec4 imageLoad(readonly volatile coherent i64image2D image, ivec2 P);
i64vec4 imageLoad(readonly volatile coherent i64image3D image, ivec3 P);
i64vec4 imageLoad(readonly volatile coherent i64imageCube image, ivec3 P);
i64vec4 imageLoad(readonly volatile coherent i64image2DRect image, ivec2 P);
i64vec4 imageLoad(readonly volatile coherent i64imageBuffer image, int P);
i64vec4 imageLoad(readonly volatile coherent i64image1DArray image, ivec2 P);
i64vec4 imageLoad(readonly volatile coherent i64image2DArray image, ivec3 P);
i64vec4 imageLoad(readonly volatile coherent i64imageCubeArray image, ivec3 P);
i64vec4 imageLoad(readonly volatile coherent i64image2DMS image, ivec2 P, int sample);
i64vec4 imageLoad(readonly volatile coherent i64image2DMSArray image, ivec3 P, int sample);
void imageStore(writeonly volatile coherent i64image1D image, int P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image2D image, ivec2 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image3D image, ivec3 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64imageCube image, ivec3 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image2DRect image, ivec2 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64imageBuffer image, int P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image1DArray image, ivec2 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image2DArray image, ivec3 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64imageCubeArray image, ivec3 P, i64vec4 data);
void imageStore(writeonly volatile coherent i64image2DMS image, ivec2 P, int sample, i64vec4 data);
void imageStore(writeonly volatile coherent i64image2DMSArray image, ivec3 P, int sample, i64vec4 data);

int imageSize(readonly writeonly volatile coherent u64image1D image);
ivec2 imageSize(readonly writeonly volatile coherent u64image2D image);
ivec3 imageSize(readonly writeonly volatile coherent u64image3D image);
ivec2 imageSize(readonly writeonly volatile coherent u64imageCube image);
ivec2 imageSize(readonly writeonly volatile coherent u64image2DRect image);
int imageSize(readonly writeonly volatile coherent u64imageBuffer image);
ivec2 imageSize(readonly writeonly volatile coherent u64image1DArray image);
ivec3 imageSize(readonly writeonly volatile coherent u64image2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent u64imageCubeArray image);
ivec2 imageSize(readonly writeonly volatile coherent u64image2DMS image);
ivec3 imageSize(readonly writeonly volatile coherent u64image2DMSArray image);
int imageSamples(readonly writeonly volatile coherent u64image2DMS image);
int imageSamples(readonly writeonly volatile coherent u64image2DMSArray image);
u64vec4 imageLoad(readonly volatile coherent u64image1D image, int P);
u64vec4 imageLoad(readonly volatile coherent u64image2D image, ivec2 P);
u64vec4 imageLoad(readonly volatile coherent u64image3D image, ivec3 P);
u64vec4 imageLoad(readonly volatile coherent u64imageCube image, ivec3 P);
u64vec4 imageLoad(readonly volatile coherent u64image2DRect image, ivec2 P);
u64vec4 imageLoad(readonly volatile coherent u64imageBuffer image, int P);
u64vec4 imageLoad(readonly volatile coherent u64image1DArray image, ivec2 P);
u64vec4 imageLoad(readonly volatile coherent u64image2DArray image, ivec3 P);
u64vec4 imageLoad(readonly volatile coherent u64imageCubeArray image, ivec3 P);
u64vec4 imageLoad(readonly volatile coherent u64image2DMS image, ivec2 P, int sample);
u64vec4 imageLoad(readonly volatile coherent u64image2DMSArray image, ivec3 P, int sample);
void imageStore(writeonly volatile coherent u64image1D image, int P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image2D image, ivec2 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image3D image, ivec3 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64imageCube image, ivec3 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image2DRect image, ivec2 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64imageBuffer image, int P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image1DArray image, ivec2 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image2DArray image, ivec3 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64imageCubeArray image, ivec3 P, u64vec4 data);
void imageStore(writeonly volatile coherent u64image2DMS image, ivec2 P, int sample, u64vec4 data);
void imageStore(writeonly volatile coherent u64image2DMSArray image, ivec3 P, int sample, u64vec4 data);

__glsld_syscmd_end_context__;

__glsld_syscmd_begin_context__;
__glsld_syscmd_require_extension__ GL_EXT_shader_explicit_arithmetic_types_float16;

int imageSize(readonly writeonly volatile coherent f16image1D image);
ivec2 imageSize(readonly writeonly volatile coherent f16image2D image);
ivec3 imageSize(readonly writeonly volatile coherent f16image3D image);
ivec2 imageSize(readonly writeonly volatile coherent f16imageCube image);
ivec2 imageSize(readonly writeonly volatile coherent f16image2DRect image);
int imageSize(readonly writeonly volatile coherent f16imageBuffer image);
ivec2 imageSize(readonly writeonly volatile coherent f16image1DArray image);
ivec3 imageSize(readonly writeonly volatile coherent f16image2DArray image);
ivec3 imageSize(readonly writeonly volatile coherent f16imageCubeArray image);
ivec2 imageSize(readonly writeonly volatile coherent f16image2DMS image);
ivec3 imageSize(readonly writeonly volatile coherent f16image2DMSArray image);
int imageSamples(readonly writeonly volatile coherent f16image2DMS image);
int imageSamples(readonly writeonly volatile coherent f16image2DMSArray image);
f16vec4 imageLoad(readonly volatile coherent f16image1D image, int P);
f16vec4 imageLoad(readonly volatile coherent f16image2D image, ivec2 P);
f16vec4 imageLoad(readonly volatile coherent f16image3D image, ivec3 P);
f16vec4 imageLoad(readonly volatile coherent f16imageCube image, ivec3 P);
f16vec4 imageLoad(readonly volatile coherent f16image2DRect image, ivec2 P);
f16vec4 imageLoad(readonly volatile coherent f16imageBuffer image, int P);
f16vec4 imageLoad(readonly volatile coherent f16image1DArray image, ivec2 P);
f16vec4 imageLoad(readonly volatile coherent f16image2DArray image, ivec3 P);
f16vec4 imageLoad(readonly volatile coherent f16imageCubeArray image, ivec3 P);
f16vec4 imageLoad(readonly volatile coherent f16image2DMS image, ivec2 P, int sample);
f16vec4 imageLoad(readonly volatile coherent f16image2DMSArray image, ivec3 P, int sample);
void imageStore(writeonly volatile coherent f16image1D image, int P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image2D image, ivec2 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image3D image, ivec3 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16imageCube image, ivec3 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image2DRect image, ivec2 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16imageBuffer image, int P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image1DArray image, ivec2 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image2DArray image, ivec3 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16imageCubeArray image, ivec3 P, f16vec4 data);
void imageStore(writeonly volatile coherent f16image2DMS image, ivec2 P, int sample, f16vec4 data);
void imageStore(writeonly volatile coherent f16image2DMSArray image, ivec3 P, int sample, f16vec4 data);

__glsld_syscmd_end_context__;
