__glsld_syscmd_begin_context__;
__glsld_syscmd_require_extension__ GL_KHR_memory_scope_semantics;

float imageAtomicAdd(volatile coherent image1D image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image2D image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image3D image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent imageBuffer image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicAdd(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAdd(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image1D image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image2D image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image3D image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent imageBuffer image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicMin(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMin(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image1D image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image2D image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image3D image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent imageBuffer image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicMax(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicMax(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicAnd(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicAnd(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicOr(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicOr(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicXor(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicXor(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image1D image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage1D image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage1D image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image2D image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage2D image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage2D image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image3D image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage3D image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage3D image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimageCube image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimageCube image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage2DRect image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage2DRect image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent imageBuffer image, int P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimageBuffer image, int P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimageBuffer image, int P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage1DArray image, ivec2 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage1DArray image, ivec2 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage2DArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage2DArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimageCubeArray image, ivec3 P, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimageCubeArray image, ivec3 P, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
highp int imageAtomicExchange(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicExchange(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage1D image, int P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage1D image, int P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage2D image, ivec2 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage2D image, ivec2 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage3D image, ivec3 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage3D image, ivec3 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimageCube image, ivec3 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimageCube image, ivec3 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage2DRect image, ivec2 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage2DRect image, ivec2 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimageBuffer image, int P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimageBuffer image, int P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage1DArray image, ivec2 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage1DArray image, ivec2 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage2DArray image, ivec3 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage2DArray image, ivec3 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimageCubeArray image, ivec3 P, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimageCubeArray image, ivec3 P, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage2DMS image, ivec2 P, int sample_, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage2DMS image, ivec2 P, int sample_, highp uint compare, highp uint data, int scope, int storage, int semantic);
highp int imageAtomicCompSwap(volatile coherent iimage2DMSArray image, ivec3 P, int sample_, highp int compare, highp int data, int scope, int storage, int semantic);
highp uint imageAtomicCompSwap(volatile coherent uimage2DMSArray image, ivec3 P, int sample_, highp uint compare, highp uint data, int scope, int storage, int semantic);

__glsld_syscmd_begin_context__;
__glsld_syscmd_require_extension__ GL_KHR_memory_scope_semantics GL_EXT_shader_explicit_arithmetic_types_int64;

highp int64_t imageAtomicAdd(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAdd(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMin(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicMax(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicAnd(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicOr(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicXor(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image1D image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image2D image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image3D image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64imageCube image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image2DRect image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64imageBuffer image, int P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image1DArray image, ivec2 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image2DArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicExchange(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image1D image, int P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image2D image, ivec2 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image3D image, ivec3 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64imageCube image, ivec3 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image2DRect image, ivec2 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64imageBuffer image, int P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image1DArray image, ivec2 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image2DArray image, ivec3 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64imageCubeArray image, ivec3 P, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image2DMS image, ivec2 P, int sample_, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);
highp int64_t imageAtomicCompSwap(volatile coherent i64image2DMSArray image, ivec3 P, int sample_, highp int64_t compare, highp int64_t data, int scope, int storage, int semantic);

highp uint64_t imageAtomicAdd(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAdd(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMin(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicMax(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicAnd(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicOr(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicXor(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image1D image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image2D image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image3D image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64imageCube image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64imageBuffer image, int P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicExchange(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image1D image, int P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image2D image, ivec2 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image3D image, ivec3 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64imageCube image, ivec3 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image2DRect image, ivec2 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64imageBuffer image, int P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image1DArray image, ivec2 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image2DArray image, ivec3 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64imageCubeArray image, ivec3 P, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image2DMS image, ivec2 P, int sample_, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);
highp uint64_t imageAtomicCompSwap(volatile coherent u64image2DMSArray image, ivec3 P, int sample_, highp uint64_t compare, highp uint64_t data, int scope, int storage, int semantic);

__glsld_syscmd_end_context__;

__glsld_syscmd_begin_context__;
__glsld_syscmd_require_extension__ GL_KHR_memory_scope_semantics GL_EXT_shader_explicit_arithmetic_types_float16;

float imageAtomicAdd(volatile coherent f16image1D image, int P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image2D image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image3D image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16imageBuffer image, int P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicAdd(volatile coherent f16image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image1D image, int P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image2D image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image3D image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16imageBuffer image, int P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicMin(volatile coherent f16image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image1D image, int P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image2D image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image3D image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16imageBuffer image, int P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicMax(volatile coherent f16image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image1D image, int P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image2D image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image3D image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16imageCube image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image2DRect image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16imageBuffer image, int P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image1DArray image, ivec2 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image2DArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16imageCubeArray image, ivec3 P, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image2DMS image, ivec2 P, int sample_, float data, int scope, int storage, int semantic);
float imageAtomicExchange(volatile coherent f16image2DMSArray image, ivec3 P, int sample_, float data, int scope, int storage, int semantic);

__glsld_syscmd_end_context__;
