// FIXME: this file needs major revision

float texture(sampler2DShadow sampler_,vec3 P);
float texture(samplerCubeShadow sampler_,vec4 P);
float texture(sampler2DRectShadow sampler_,vec3 P);
float texture(sampler1DArrayShadow sampler_,vec3 P);
float texture(sampler2DArrayShadow sampler_,vec4 P);
float texture(samplerCubeArrayShadow sampler_,vec4 P,float bias);
vec4 texture(sampler1D sampler_,float P);
ivec4 texture(isampler1D sampler_,float P);
uvec4 texture(usampler1D sampler_,float P);
vec4 texture(sampler2D sampler_,vec2 P);
ivec4 texture(isampler2D sampler_,vec2 P);
uvec4 texture(usampler2D sampler_,vec2 P);
vec4 texture(sampler3D sampler_,vec3 P);
ivec4 texture(isampler3D sampler_,vec3 P);
uvec4 texture(usampler3D sampler_,vec3 P);
vec4 texture(samplerCube sampler_,vec3 P);
ivec4 texture(isamplerCube sampler_,vec3 P);
uvec4 texture(usamplerCube sampler_,vec3 P);
vec4 texture(sampler2DRect sampler_,vec2 P);
ivec4 texture(isampler2DRect sampler_,vec2 P);
uvec4 texture(usampler2DRect sampler_,vec2 P);
vec4 texture(sampler1DArray sampler_,vec2 P);
ivec4 texture(isampler1DArray sampler_,vec2 P);
uvec4 texture(usampler1DArray sampler_,vec2 P);
vec4 texture(sampler2DArray sampler_,vec3 P);
ivec4 texture(isampler2DArray sampler_,vec3 P);
uvec4 texture(usampler2DArray sampler_,vec3 P);
vec4 texture(samplerCubeArray sampler_,vec4 P);
ivec4 texture(isamplerCubeArray sampler_,vec4 P);
uvec4 texture(usamplerCubeArray sampler_,vec4 P);
float texture(sampler1DShadow sampler_,vec3 P);
vec4 textureProj(sampler1D sampler_,vec2 P);
vec4 textureProj(sampler1D sampler_,vec4 P);
float textureProj(sampler2DRectShadow sampler_,vec4 P);
ivec4 textureProj(isampler1D sampler_,vec2 P);
ivec4 textureProj(isampler1D sampler_,vec4 P);
uvec4 textureProj(usampler1D sampler_,vec2 P);
uvec4 textureProj(usampler1D sampler_,vec4 P);
vec4 textureProj(sampler2D sampler_,vec3 P);
vec4 textureProj(sampler2D sampler_,vec4 P);
ivec4 textureProj(isampler2D sampler_,vec3 P);
ivec4 textureProj(isampler2D sampler_,vec4 P);
uvec4 textureProj(usampler2D sampler_,vec3 P);
uvec4 textureProj(usampler2D sampler_,vec4 P);
vec4 textureProj(sampler3D sampler_,vec4 P);
ivec4 textureProj(isampler3D sampler_,vec4 P);
uvec4 textureProj(usampler3D sampler_,vec4 P);
vec4 textureProj(sampler2DRect sampler_,vec3 P);
vec4 textureProj(sampler2DRect sampler_,vec4 P);
ivec4 textureProj(isampler2DRect sampler_,vec3 P);
ivec4 textureProj(isampler2DRect sampler_,vec4 P);
uvec4 textureProj(usampler2DRect sampler_,vec3 P);
uvec4 textureProj(usampler2DRect sampler_,vec4 P);
float textureProj(sampler1DShadow sampler_,vec4 P);
float textureProj(sampler2DShadow sampler_,vec4 P);
float textureLod(sampler1DArrayShadow sampler_,vec3 P,float lod);
vec4 textureLod(sampler1D sampler_,float P,float lod);
ivec4 textureLod(isampler1D sampler_,float P,float lod);
uvec4 textureLod(usampler1D sampler_,float P,float lod);
vec4 textureLod(sampler2D sampler_,vec2 P,float lod);
ivec4 textureLod(isampler2D sampler_,vec2 P,float lod);
uvec4 textureLod(usampler2D sampler_,vec2 P,float lod);
vec4 textureLod(sampler3D sampler_,vec3 P,float lod);
ivec4 textureLod(isampler3D sampler_,vec3 P,float lod);
uvec4 textureLod(usampler3D sampler_,vec3 P,float lod);
vec4 textureLod(samplerCube sampler_,vec3 P,float lod);
ivec4 textureLod(isamplerCube sampler_,vec3 P,float lod);
uvec4 textureLod(usamplerCube sampler_,vec3 P,float lod);
vec4 textureLod(sampler1DArray sampler_,vec2 P,float lod);
ivec4 textureLod(isampler1DArray sampler_,vec2 P,float lod);
uvec4 textureLod(usampler1DArray sampler_,vec2 P,float lod);
vec4 textureLod(sampler2DArray sampler_,vec3 P,float lod);
ivec4 textureLod(isampler2DArray sampler_,vec3 P,float lod);
uvec4 textureLod(usampler2DArray sampler_,vec3 P,float lod);
vec4 textureLod(samplerCubeArray sampler_,vec4 P,float lod);
ivec4 textureLod(isamplerCubeArray sampler_,vec4 P,float lod);
uvec4 textureLod(usamplerCubeArray sampler_,vec4 P,float lod);
float textureLod(sampler1DShadow sampler_,vec3 P,float lod);
float textureLod(sampler2DShadow sampler_,vec3 P,float lod);
ivec4 textureOffset(isampler1D sampler_,float P,int offset);
uvec4 textureOffset(usampler1D sampler_,float P,int offset);
vec4 textureOffset(sampler1D sampler_,float P,int offset);
vec4 textureOffset(sampler2D sampler_,vec2 P,ivec2 offset);
ivec4 textureOffset(isampler2D sampler_,vec2 P,ivec2 offset);
uvec4 textureOffset(usampler2D sampler_,vec2 P,ivec2 offset);
vec4 textureOffset(sampler3D sampler_,vec3 P,ivec3 offset);
ivec4 textureOffset(isampler3D sampler_,vec3 P,ivec3 offset);
uvec4 textureOffset(usampler3D sampler_,vec3 P,ivec3 offset);
vec4 textureOffset(sampler2DRect sampler_,vec2 P,ivec2 offset);
ivec4 textureOffset(isampler2DRect sampler_,vec2 P,ivec2 offset);
uvec4 textureOffset(usampler2DRect sampler_,vec2 P,ivec2 offset);
vec4 textureOffset(sampler1DArray sampler_,vec2 P,int offset);
ivec4 textureOffset(isampler1DArray sampler_,vec2 P,int offset);
uvec4 textureOffset(usampler1DArray sampler_,vec2 P,int offset);
vec4 textureOffset(sampler2DArray sampler_,vec3 P,ivec2 offset);
ivec4 textureOffset(isampler2DArray sampler_,vec3 P,ivec2 offset);
uvec4 textureOffset(usampler2DArray sampler_,vec3 P,ivec2 offset);
float textureOffset(sampler1DShadow sampler_,vec3 P,int offset);
float textureOffset(sampler2DShadow sampler_,vec3 P,ivec2 offset);
float textureOffset(sampler2DRectShadow sampler_,vec3 P,ivec2 offset);
float textureOffset(sampler1DArrayShadow sampler_,vec3 P,int offset);
float textureOffset(sampler2DArrayShadow sampler_,vec4 P,ivec2 offset);
vec4 texelFetch(sampler1D sampler_,int P,int lod);
ivec4 texelFetch(isampler1D sampler_,int P,int lod);
uvec4 texelFetch(usampler1D sampler_,int P,int lod);
vec4 texelFetch(sampler2D sampler_,ivec2 P,int lod);
ivec4 texelFetch(isampler2D sampler_,ivec2 P,int lod);
uvec4 texelFetch(usampler2D sampler_,ivec2 P,int lod);
vec4 texelFetch(sampler3D sampler_,ivec3 P,int lod);
ivec4 texelFetch(isampler3D sampler_,ivec3 P,int lod);
uvec4 texelFetch(usampler3D sampler_,ivec3 P,int lod);
vec4 texelFetch(sampler2DRect sampler_,ivec2 P);
ivec4 texelFetch(isampler2DRect sampler_,ivec2 P);
uvec4 texelFetch(usampler2DRect sampler_,ivec2 P);
vec4 texelFetch(samplerBuffer sampler_,int P);
ivec4 texelFetch(isamplerBuffer sampler_,int P);
uvec4 texelFetch(usamplerBuffer sampler_,int P);
vec4 texelFetch(sampler1DArray sampler_,ivec2 P,int lod);
ivec4 texelFetch(isampler1DArray sampler_,ivec2 P,int lod);
uvec4 texelFetch(usampler1DArray sampler_,ivec2 P,int lod);
vec4 texelFetch(sampler2DArray sampler_,ivec3 P,int lod);
ivec4 texelFetch(isampler2DArray sampler_,ivec3 P,int lod);
uvec4 texelFetch(usampler2DArray sampler_,ivec3 P,int lod);
vec4 texelFetch(sampler2DMS sampler_,ivec2 P,int lod);
ivec4 texelFetch(isampler2DMS sampler_,ivec2 P,int lod);
uvec4 texelFetch(usampler2DMS sampler_,ivec2 P,int lod);
vec4 texelFetch(sampler2DMSArray sampler_,ivec3 P,int lod);
ivec4 texelFetch(isampler2DMSArray sampler_,ivec3 P,int lod);
uvec4 texelFetch(usampler2DMSArray sampler_,ivec3 P,int lod);
vec4 texelFetchOffset(sampler1D sampler_,int P,int lod,int offset);
ivec4 texelFetchOffset(isampler1D sampler_,int P,int lod,int offset);
uvec4 texelFetchOffset(usampler1D sampler_,int P,int lod,int offset);
vec4 texelFetchOffset(sampler2D sampler_,ivec2 P,int lod,ivec2 offset);
ivec4 texelFetchOffset(isampler2D sampler_,ivec2 P,int lod,ivec2 offset);
uvec4 texelFetchOffset(usampler2D sampler_,ivec2 P,int lod,ivec2 offset);
vec4 texelFetchOffset(sampler3D sampler_,ivec3 P,int lod,ivec3 offset);
ivec4 texelFetchOffset(isampler3D sampler_,ivec3 P,int lod,ivec3 offset);
uvec4 texelFetchOffset(usampler3D sampler_,ivec3 P,int lod,ivec3 offset);
vec4 texelFetchOffset(sampler2DRect sampler_,ivec2 P,ivec2 offset);
ivec4 texelFetchOffset(isampler2DRect sampler_,ivec2 P,ivec2 offset);
uvec4 texelFetchOffset(usampler2DRect sampler_,ivec2 P,ivec2 offset);
vec4 texelFetchOffset(sampler1DArray sampler_,ivec2 P,int lod,int offset);
ivec4 texelFetchOffset(isampler1DArray sampler_,ivec2 P,int lod,int offset);
uvec4 texelFetchOffset(usampler1DArray sampler_,ivec2 P,int lod,int offset);
vec4 texelFetchOffset(sampler2DArray sampler_,ivec3 P,int lod,ivec2 offset);
ivec4 texelFetchOffset(isampler2DArray sampler_,ivec3 P,int lod,ivec2 offset);
uvec4 texelFetchOffset(usampler2DArray sampler_,ivec3 P,int lod,ivec2 offset);
vec4 textureProjOffset(sampler1D sampler_,vec2 P,int offset);
vec4 textureProjOffset(sampler1D sampler_,vec4 P,int offset);
ivec4 textureProjOffset(isampler1D sampler_,vec2 P,int offset);
ivec4 textureProjOffset(isampler1D sampler_,vec4 P,int offset);
uvec4 textureProjOffset(usampler1D sampler_,vec2 P,int offset);
uvec4 textureProjOffset(usampler1D sampler_,vec4 P,int offset);
vec4 textureProjOffset(sampler2D sampler_,vec3 P,ivec2 offset);
vec4 textureProjOffset(sampler2D sampler_,vec4 P,ivec2 offset);
ivec4 textureProjOffset(isampler2D sampler_,vec3 P,ivec2 offset);
ivec4 textureProjOffset(isampler2D sampler_,vec4 P,ivec2 offset);
uvec4 textureProjOffset(usampler2D sampler_,vec3 P,ivec2 offset);
uvec4 textureProjOffset(usampler2D sampler_,vec4 P,ivec2 offset);
vec4 textureProjOffset(sampler3D sampler_,vec4 P,ivec3 offset);
ivec4 textureProjOffset(isampler3D sampler_,vec4 P,ivec3 offset);
uvec4 textureProjOffset(usampler3D sampler_,vec4 P,ivec3 offset);
vec4 textureProjOffset(sampler2DRect sampler_,vec3 P,ivec2 offset);
vec4 textureProjOffset(sampler2DRect sampler_,vec4 P,ivec2 offset);
ivec4 textureProjOffset(isampler2DRect sampler_,vec3 P,ivec2 offset);
ivec4 textureProjOffset(isampler2DRect sampler_,vec4 P,ivec2 offset);
uvec4 textureProjOffset(usampler2DRect sampler_,vec3 P,ivec2 offset);
uvec4 textureProjOffset(usampler2DRect sampler_,vec4 P,ivec2 offset);
float textureProjOffset(sampler1DShadow sampler_,vec4 P,int offset);
float textureProjOffset(sampler2DShadow sampler_,vec4 P,ivec2 offset);
float textureProjOffset(sampler2DRectShadow sampler_,vec4 P,ivec2 offset);
vec4 textureLodOffset(sampler1D sampler_,float P,float lod,int offset);
ivec4 textureLodOffset(isampler1D sampler_,float P,float lod,int offset);
uvec4 textureLodOffset(usampler1D sampler_,float P,float lod,int offset);
vec4 textureLodOffset(sampler2D sampler_,vec2 P,float lod,ivec2 offset);
ivec4 textureLodOffset(isampler2D sampler_,vec2 P,float lod,ivec2 offset);
uvec4 textureLodOffset(usampler2D sampler_,vec2 P,float lod,ivec2 offset);
vec4 textureLodOffset(sampler3D sampler_,vec3 P,float lod,ivec3 offset);
ivec4 textureLodOffset(isampler3D sampler_,vec3 P,float lod,ivec3 offset);
uvec4 textureLodOffset(usampler3D sampler_,vec3 P,float lod,ivec3 offset);
vec4 textureLodOffset(sampler1DArray sampler_,vec2 P,float lod,int offset);
ivec4 textureLodOffset(isampler1DArray sampler_,vec2 P,float lod,int offset);
uvec4 textureLodOffset(usampler1DArray sampler_,vec2 P,float lod,int offset);
vec4 textureLodOffset(sampler2DArray sampler_,vec3 P,float lod,ivec2 offset);
ivec4 textureLodOffset(isampler2DArray sampler_,vec3 P,float lod,ivec2 offset);
uvec4 textureLodOffset(usampler2DArray sampler_,vec3 P,float lod,ivec2 offset);
float textureLodOffset(sampler1DShadow sampler_,vec3 P,float lod,int offset);
float textureLodOffset(sampler2DShadow sampler_,vec3 P,float lod,ivec2 offset);
float textureLodOffset(sampler1DArrayShadow sampler_,vec3 P,float lod,int offset);
vec4 textureProjLod(sampler1D sampler_,vec2 P,float lod);
vec4 textureProjLod(sampler1D sampler_,vec4 P,float lod);
ivec4 textureProjLod(isampler1D sampler_,vec2 P,float lod);
ivec4 textureProjLod(isampler1D sampler_,vec4 P,float lod);
uvec4 textureProjLod(usampler1D sampler_,vec2 P,float lod);
uvec4 textureProjLod(usampler1D sampler_,vec4 P,float lod);
vec4 textureProjLod(sampler2D sampler_,vec3 P,float lod);
vec4 textureProjLod(sampler2D sampler_,vec4 P,float lod);
ivec4 textureProjLod(isampler2D sampler_,vec3 P,float lod);
ivec4 textureProjLod(isampler2D sampler_,vec4 P,float lod);
uvec4 textureProjLod(usampler2D sampler_,vec3 P,float lod);
uvec4 textureProjLod(usampler2D sampler_,vec4 P,float lod);
vec4 textureProjLod(sampler3D sampler_,vec4 P,float lod);
ivec4 textureProjLod(isampler3D sampler_,vec4 P,float lod);
uvec4 textureProjLod(usampler3D sampler_,vec4 P,float lod);
float textureProjLod(sampler1DShadow sampler_,vec4 P,float lod);
float textureProjLod(sampler2DShadow sampler_,vec4 P,float lod);
vec4 textureProjLodOffset(sampler1D sampler_,vec2 P,float lod,int offset);
vec4 textureProjLodOffset(sampler1D sampler_,vec4 P,float lod,int offset);
ivec4 textureProjLodOffset(isampler1D sampler_,vec2 P,float lod,int offset);
ivec4 textureProjLodOffset(isampler1D sampler_,vec4 P,float lod,int offset);
uvec4 textureProjLodOffset(usampler1D sampler_,vec2 P,float lod,int offset);
uvec4 textureProjLodOffset(usampler1D sampler_,vec4 P,float lod,int offset);
vec4 textureProjLodOffset(sampler2D sampler_,vec3 P,float lod,ivec2 offset);
vec4 textureProjLodOffset(sampler2D sampler_,vec4 P,float lod,ivec2 offset);
ivec4 textureProjLodOffset(isampler2D sampler_,vec3 P,float lod,ivec2 offset);
ivec4 textureProjLodOffset(isampler2D sampler_,vec4 P,float lod,ivec2 offset);
uvec4 textureProjLodOffset(usampler2D sampler_,vec3 P,float lod,ivec2 offset);
uvec4 textureProjLodOffset(usampler2D sampler_,vec4 P,float lod,ivec2 offset);
vec4 textureProjLodOffset(sampler3D sampler_,vec4 P,float lod,ivec3 offset);
ivec4 textureProjLodOffset(isampler3D sampler_,vec4 P,float lod,ivec3 offset);
uvec4 textureProjLodOffset(usampler3D sampler_,vec4 P,float lod,ivec3 offset);
float textureProjLodOffset(sampler1DShadow sampler_,vec4 P,float lod,int offset);
float textureProjLodOffset(sampler2DShadow sampler_,vec4 P,float lod,ivec2 offset);
vec4 textureGrad(sampler1D sampler_,float P,float dPdx,float dPdy);
ivec4 textureGrad(isampler1D sampler_,float P,float dPdx,float dPdy);
uvec4 textureGrad(usampler1D sampler_,float P,float dPdx,float dPdy);
vec4 textureGrad(sampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
ivec4 textureGrad(isampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
uvec4 textureGrad(usampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
vec4 textureGrad(sampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
ivec4 textureGrad(isampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
uvec4 textureGrad(usampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
vec4 textureGrad(samplerCube sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
ivec4 textureGrad(isamplerCube sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
uvec4 textureGrad(usamplerCube sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
vec4 textureGrad(sampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
ivec4 textureGrad(isampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
uvec4 textureGrad(usampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
vec4 textureGrad(sampler1DArray sampler_,vec2 P,float dPdx,float dPdy);
ivec4 textureGrad(isampler1DArray sampler_,vec2 P,float dPdx,float dPdy);
uvec4 textureGrad(usampler1DArray sampler_,vec2 P,float dPdx,float dPdy);
vec4 textureGrad(sampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
ivec4 textureGrad(isampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
uvec4 textureGrad(usampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
vec4 textureGrad(samplerCubeArray sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
ivec4 textureGrad(isamplerCubeArray sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
uvec4 textureGrad(usamplerCubeArray sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
float textureGrad(sampler1DShadow sampler_,vec3 P,float dPdx,float dPdy);
float textureGrad(sampler2DShadow sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
float textureGrad(samplerCubeShadow sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
float textureGrad(sampler2DRectShadow sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
float textureGrad(sampler1DArrayShadow sampler_,vec3 P,float dPdx,float dPdy);
float textureGrad(sampler2DArrayShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
float textureGrad(samplerCubeArrayShadow sampler_,vec4 P,float dPdx,vec3 dPdy,vec3);
vec4 textureGradOffset(sampler1D sampler_,float P,float dPdx,float dPdy,int offset);
ivec4 textureGradOffset(isampler1D sampler_,float P,float dPdx,float dPdy,int offset);
uvec4 textureGradOffset(usampler1D sampler_,float P,float dPdx,float dPdy,int offset);
vec4 textureGradOffset(sampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureGradOffset(isampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureGradOffset(usampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureGradOffset(sampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
ivec4 textureGradOffset(isampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
uvec4 textureGradOffset(usampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
vec4 textureGradOffset(sampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureGradOffset(isampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureGradOffset(usampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureGradOffset(sampler1DArray sampler_,vec2 P,float dPdx,float dPdy,int offset);
ivec4 textureGradOffset(isampler1DArray sampler_,vec2 P,float dPdx,float dPdy,int offset);
uvec4 textureGradOffset(usampler1DArray sampler_,vec2 P,float dPdx,float dPdy,int offset);
vec4 textureGradOffset(sampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureGradOffset(isampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureGradOffset(usampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
float textureGradOffset(sampler1DShadow sampler_,vec3 P,float dPdx,float dPdy,int offset);
float textureGradOffset(sampler2DShadow sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
float textureGradOffset(sampler2DRectShadow sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
float textureGradOffset(sampler1DArrayShadow sampler_,vec3 P,float dPdx,float dPdy,int offset);
float textureGradOffset(sampler2DArrayShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureProjGrad(sampler1D sampler_,vec2 P,float dPdx,float dPdy);
vec4 textureProjGrad(sampler1D sampler_,vec4 P,float dPdx,float dPdy);
ivec4 textureProjGrad(isampler1D sampler_,vec2 P,float dPdx,float dPdy);
ivec4 textureProjGrad(isampler1D sampler_,vec4 P,float dPdx,float dPdy);
uvec4 textureProjGrad(usampler1D sampler_,vec2 P,float dPdx,float dPdy);
uvec4 textureProjGrad(usampler1D sampler_,vec4 P,float dPdx,float dPdy);
vec4 textureProjGrad(sampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
vec4 textureProjGrad(sampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
ivec4 textureProjGrad(isampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
ivec4 textureProjGrad(isampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
uvec4 textureProjGrad(usampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
uvec4 textureProjGrad(usampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
vec4 textureProjGrad(sampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
ivec4 textureProjGrad(isampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
uvec4 textureProjGrad(usampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
vec4 textureProjGrad(sampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
vec4 textureProjGrad(sampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
ivec4 textureProjGrad(isampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
ivec4 textureProjGrad(isampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
uvec4 textureProjGrad(usampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
uvec4 textureProjGrad(usampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
float textureProjGrad(sampler1DShadow sampler_,vec4 P,float dPdx,float dPdy);
float textureProjGrad(sampler2DShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
float textureProjGrad(sampler2DRectShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy);
vec4 textureProjGradOffset(sampler1D sampler_,vec2 P,float dPdx,float dPdy,int offset);
vec4 textureProjGradOffset(sampler1D sampler_,vec4 P,float dPdx,float dPdy,int offset);
ivec4 textureProjGradOffset(isampler1D sampler_,vec2 P,float dPdx,float dPdy,int offset);
ivec4 textureProjGradOffset(isampler1D sampler_,vec4 P,float dPdx,float dPdy,int offset);
uvec4 textureProjGradOffset(usampler1D sampler_,vec2 P,float dPdx,float dPdy,int offset);
uvec4 textureProjGradOffset(usampler1D sampler_,vec4 P,float dPdx,float dPdy,int offset);
vec4 textureProjGradOffset(sampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureProjGradOffset(sampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureProjGradOffset(isampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureProjGradOffset(isampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureProjGradOffset(usampler2D sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureProjGradOffset(usampler2D sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureProjGradOffset(sampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
ivec4 textureProjGradOffset(isampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
uvec4 textureProjGradOffset(usampler3D sampler_,vec4 P,vec3 dPdx,vec3 dPdy,ivec3 offset);
vec4 textureProjGradOffset(sampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
vec4 textureProjGradOffset(sampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureProjGradOffset(isampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
ivec4 textureProjGradOffset(isampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureProjGradOffset(usampler2DRect sampler_,vec3 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
uvec4 textureProjGradOffset(usampler2DRect sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
float textureProjGradOffset(sampler1DShadow sampler_,vec4 P,float dPdx,float dPdy,int offset);
float textureProjGradOffset(sampler2DShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);
float textureProjGradOffset(sampler2DRectShadow sampler_,vec4 P,vec2 dPdx,vec2 dPdy,ivec2 offset);

#if __GLSLD_FEATURE_ENABLE_FLOAT16_TYPE

float16_t texture(f16sampler2DShadow,vec3);
float16_t texture(f16sampler2DShadow,f16vec2,float);
float16_t texture(f16samplerCubeShadow,vec4);
float16_t texture(f16samplerCubeShadow,f16vec3,float);
float16_t texture(f16sampler2DRectShadow,vec3);
float16_t texture(f16sampler2DRectShadow,f16vec2,float);
float16_t texture(f16sampler1DArrayShadow,vec3);
float16_t texture(f16sampler1DArrayShadow,f16vec2,float);
float16_t texture(f16sampler2DArrayShadow,vec4);
float16_t texture(f16sampler2DArrayShadow,f16vec3,float);
float16_t texture(f16samplerCubeArrayShadow,vec4,float);
float16_t texture(f16samplerCubeArrayShadow,f16vec4,float);
f16vec4 texture(f16sampler1D,float);
f16vec4 texture(f16sampler1D,float16_t);
f16vec4 texture(f16sampler2D,vec2);
f16vec4 texture(f16sampler2D,f16vec2);
f16vec4 texture(f16sampler3D,vec3);
f16vec4 texture(f16sampler3D,f16vec3);
f16vec4 texture(f16samplerCube,vec3);
f16vec4 texture(f16samplerCube,f16vec3);
f16vec4 texture(f16sampler2DRect,vec2);
f16vec4 texture(f16sampler2DRect,f16vec2);
f16vec4 texture(f16sampler1DArray,vec2);
f16vec4 texture(f16sampler1DArray,f16vec2);
f16vec4 texture(f16sampler2DArray,vec3);
f16vec4 texture(f16sampler2DArray,f16vec3);
f16vec4 texture(f16samplerCubeArray,vec4);
f16vec4 texture(f16samplerCubeArray,f16vec4);
float16_t texture(f16sampler1DShadow sampler_,vec3 P);
float16_t texture(f16sampler1DShadow sampler_,f16vec2 P,float compare);
float16_t textureProj(f16sampler2DRectShadow sampler_,vec4 P);
float16_t textureProj(f16sampler2DRectShadow sampler_,f16vec3 P,float bias);
float16_t textureProj(f16sampler2DShadow sampler_,vec4 P);
float16_t textureProj(f16sampler2DShadow sampler_,f16vec3 P,float bias);
f16vec4 textureProj(f16sampler1D sampler_,vec2 P);
f16vec4 textureProj(f16sampler1D sampler_,f16vec2 P);
f16vec4 textureProj(f16sampler1D sampler_,vec4 P);
f16vec4 textureProj(f16sampler1D sampler_,f16vec4 P);
f16vec4 textureProj(f16sampler2D sampler_,vec3 P);
f16vec4 textureProj(f16sampler2D sampler_,f16vec3 P);
f16vec4 textureProj(f16sampler2D sampler_,vec4 P);
f16vec4 textureProj(f16sampler2D sampler_,f16vec4 P);
f16vec4 textureProj(f16sampler3D sampler_,vec4 P);
f16vec4 textureProj(f16sampler3D sampler_,f16vec4 P);
f16vec4 textureProj(f16sampler2DRect sampler_,vec3 P);
f16vec4 textureProj(f16sampler2DRect sampler_,f16vec3 P);
f16vec4 textureProj(f16sampler2DRect sampler_,vec4 P);
f16vec4 textureProj(f16sampler2DRect sampler_,f16vec4 P);
float16_t textureProj(f16sampler1DShadow sampler_,vec4 P);
float16_t textureProj(f16sampler1DShadow sampler_,f16vec3 P,float bias);
float16_t textureLod(f16sampler2DShadow sampler_,vec3 P,float lod);
float16_t textureLod(f16sampler2DShadow sampler_,f16vec2 P,float lod,float16_t);
float16_t textureLod(f16sampler1DArrayShadow sampler_,vec3 P,float lod);
float16_t textureLod(f16sampler1DArrayShadow sampler_,f16vec2 P,float lod,float16_t);
f16vec4 textureLod(f16sampler1D sampler_,float P,float lod);
f16vec4 textureLod(f16sampler1D sampler_,float16_t P,float16_t lod);
f16vec4 textureLod(f16sampler2D sampler_,vec2 P,float lod);
f16vec4 textureLod(f16sampler2D sampler_,f16vec2 P,float16_t lod);
f16vec4 textureLod(f16sampler3D sampler_,vec3 P,float lod);
f16vec4 textureLod(f16sampler3D sampler_,f16vec3 P,float16_t lod);
f16vec4 textureLod(f16samplerCube sampler_,vec3 P,float lod);
f16vec4 textureLod(f16samplerCube sampler_,f16vec3 P,float16_t lod);
f16vec4 textureLod(f16sampler1DArray sampler_,vec2 P,float lod);
f16vec4 textureLod(f16sampler1DArray sampler_,f16vec2 P,float16_t lod);
f16vec4 textureLod(f16sampler2DArray sampler_,vec3 P,float lod);
f16vec4 textureLod(f16sampler2DArray sampler_,f16vec3 P,float16_t lod);
f16vec4 textureLod(f16samplerCubeArray sampler_,vec4 P,float lod);
f16vec4 textureLod(f16samplerCubeArray sampler_,f16vec4 P,float16_t lod);
float16_t textureLod(f16sampler1DShadow sampler_,vec3 P,float lod);
float16_t textureLod(f16sampler1DShadow sampler_,f16vec2 P,float lod,float16_t);
f16vec4 textureOffset(f16sampler1D sampler_,float P,int offset);
f16vec4 textureOffset(f16sampler1D sampler_,float16_t P,int offset);
f16vec4 textureOffset(f16sampler2D sampler_,vec2 P,ivec2 offset);
f16vec4 textureOffset(f16sampler2D sampler_,f16vec2 P,ivec2 offset);
f16vec4 textureOffset(f16sampler3D sampler_,vec3 P,ivec3 offset);
f16vec4 textureOffset(f16sampler3D sampler_,f16vec3 P,ivec3 offset);
f16vec4 textureOffset(f16sampler2DRect sampler_,vec2 P,ivec2 offset);
f16vec4 textureOffset(f16sampler2DRect sampler_,f16vec2 P,ivec2 offset);
f16vec4 textureOffset(f16sampler1DArray sampler_,vec2 P,int offset);
f16vec4 textureOffset(f16sampler1DArray sampler_,f16vec2 P,int offset);
f16vec4 textureOffset(f16sampler2DArray sampler_,vec3 P,ivec2 offset);
f16vec4 textureOffset(f16sampler2DArray sampler_,f16vec3 P,ivec2 offset);
float16_t textureOffset(f16sampler1DShadow sampler_,vec3 P,int offset);
float16_t textureOffset(f16sampler1DShadow sampler_,f16vec2 P,float offset,int bias);
float16_t textureOffset(f16sampler2DShadow sampler_,vec3 P,ivec2 offset);
float16_t textureOffset(f16sampler2DShadow sampler_,f16vec2 P,float offset,ivec2 bias);
float16_t textureOffset(f16sampler2DRectShadow sampler_,vec3 P,ivec2 offset);
float16_t textureOffset(f16sampler2DRectShadow sampler_,f16vec2 P,float offset,ivec2 bias);
float16_t textureOffset(f16sampler1DArrayShadow sampler_,vec3 P,int offset);
float16_t textureOffset(f16sampler1DArrayShadow sampler_,f16vec2 P,float offset,int bias);
float16_t textureOffset(f16sampler2DArrayShadow sampler_,vec4 P,ivec2 offset);
float16_t textureOffset(f16sampler2DArrayShadow sampler_,f16vec3 P,float offset,ivec2 bias);
f16vec4 texelFetch(f16sampler1D sampler_,int P,int lod);
f16vec4 texelFetch(f16sampler1D sampler_,int P,int lod);
f16vec4 texelFetch(f16sampler2D sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler2D sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler3D sampler_,ivec3 P,int lod);
f16vec4 texelFetch(f16sampler3D sampler_,ivec3 P,int lod);
f16vec4 texelFetch(f16sampler2DRect sampler_,ivec2 P);
f16vec4 texelFetch(f16sampler2DRect sampler_,ivec2 P);
f16vec4 texelFetch(f16samplerBuffer sampler_,int P);
f16vec4 texelFetch(f16samplerBuffer sampler_,int P);
f16vec4 texelFetch(f16sampler1DArray sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler1DArray sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler2DArray sampler_,ivec3 P,int lod);
f16vec4 texelFetch(f16sampler2DArray sampler_,ivec3 P,int lod);
f16vec4 texelFetch(f16sampler2DMS sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler2DMS sampler_,ivec2 P,int lod);
f16vec4 texelFetch(f16sampler2DMSArray sampler_,ivec3 P,int lod);
f16vec4 texelFetch(f16sampler2DMSArray sampler_,ivec3 P,int lod);
f16vec4 texelFetchOffset(f16sampler1D sampler_,int P,int lod,int offset);
f16vec4 texelFetchOffset(f16sampler1D sampler_,int P,int lod,int offset);
f16vec4 texelFetchOffset(f16sampler2D sampler_,ivec2 P,int lod,ivec2 offset);
f16vec4 texelFetchOffset(f16sampler2D sampler_,ivec2 P,int lod,ivec2 offset);
f16vec4 texelFetchOffset(f16sampler3D sampler_,ivec3 P,int lod,ivec3 offset);
f16vec4 texelFetchOffset(f16sampler3D sampler_,ivec3 P,int lod,ivec3 offset);
f16vec4 texelFetchOffset(f16sampler2DRect sampler_,ivec2 P,ivec2 offset);
f16vec4 texelFetchOffset(f16sampler2DRect sampler_,ivec2 P,ivec2 offset);
f16vec4 texelFetchOffset(f16sampler1DArray sampler_,ivec2 P,int lod,int offset);
f16vec4 texelFetchOffset(f16sampler1DArray sampler_,ivec2 P,int lod,int offset);
f16vec4 texelFetchOffset(f16sampler2DArray sampler_,ivec3 P,int lod,ivec2 offset);
f16vec4 texelFetchOffset(f16sampler2DArray sampler_,ivec3 P,int lod,ivec2 offset);
f16vec4 textureProjOffset(f16sampler1D sampler_,vec2 P,int offset);
f16vec4 textureProjOffset(f16sampler1D sampler_,f16vec2 P,int offset);
f16vec4 textureProjOffset(f16sampler1D sampler_,vec4 P,int offset);
f16vec4 textureProjOffset(f16sampler1D sampler_,f16vec4 P,int offset);
f16vec4 textureProjOffset(f16sampler2D sampler_,vec3 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2D sampler_,f16vec3 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2D sampler_,vec4 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2D sampler_,f16vec4 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler3D sampler_,vec4 P,ivec3 offset);
f16vec4 textureProjOffset(f16sampler3D sampler_,f16vec4 P,ivec3 offset);
f16vec4 textureProjOffset(f16sampler2DRect sampler_,vec3 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2DRect sampler_,f16vec3 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2DRect sampler_,vec4 P,ivec2 offset);
f16vec4 textureProjOffset(f16sampler2DRect sampler_,f16vec4 P,ivec2 offset);
float16_t textureProjOffset(f16sampler1DShadow sampler_,vec4 P,int offset);
float16_t textureProjOffset(f16sampler1DShadow sampler_,f16vec3 P,float offset,int bias);
float16_t textureProjOffset(f16sampler2DShadow sampler_,vec4 P,ivec2 offset);
float16_t textureProjOffset(f16sampler2DShadow sampler_,f16vec3 P,float offset,ivec2 bias);
float16_t textureProjOffset(f16sampler2DRectShadow sampler_,vec4 P,ivec2 offset);
float16_t textureProjOffset(f16sampler2DRectShadow sampler_,f16vec3 P,float offset,ivec2 bias);
float16_t textureLodOffset(f16sampler1DArrayShadow sampler_,vec3 P,float lod,int offset);
f16vec4 textureLodOffset(f16sampler1D sampler_,float P,float lod,int offset);
f16vec4 textureLodOffset(f16sampler1D sampler_,float16_t P,float16_t lod,int offset);
f16vec4 textureLodOffset(f16sampler2D sampler_,vec2 P,float lod,ivec2 offset);
f16vec4 textureLodOffset(f16sampler2D sampler_,f16vec2 P,float16_t lod,ivec2 offset);
f16vec4 textureLodOffset(f16sampler3D sampler_,vec3 P,float lod,ivec3 offset);
f16vec4 textureLodOffset(f16sampler3D sampler_,f16vec3 P,float16_t lod,ivec3 offset);
f16vec4 textureLodOffset(f16sampler1DArray sampler_,vec2 P,float lod,int offset);
f16vec4 textureLodOffset(f16sampler1DArray sampler_,f16vec2 P,float16_t lod,int offset);
f16vec4 textureLodOffset(f16sampler2DArray sampler_,vec3 P,float lod,ivec2 offset);
f16vec4 textureLodOffset(f16sampler2DArray sampler_,f16vec3 P,float16_t lod,ivec2 offset);
float16_t textureLodOffset(f16sampler1DShadow sampler_,vec3 P,float lod,int offset);
float16_t textureLodOffset(f16sampler1DShadow sampler_,f16vec2 P,float lod,float16_t offset,int);
float16_t textureLodOffset(f16sampler2DShadow sampler_,vec3 P,float lod,ivec2 offset);
float16_t textureLodOffset(f16sampler2DShadow sampler_,f16vec2 P,float lod,float16_t offset,ivec2);
float16_t textureLodOffset(f16sampler1DArrayShadow sampler_,f16vec2 P,float lod,float16_t offset,int);
f16vec4 textureProjLod(f16sampler1D sampler_,vec2 P,float lod);
f16vec4 textureProjLod(f16sampler1D sampler_,f16vec2 P,float16_t lod);
f16vec4 textureProjLod(f16sampler1D sampler_,vec4 P,float lod);
f16vec4 textureProjLod(f16sampler1D sampler_,f16vec4 P,float16_t lod);
f16vec4 textureProjLod(f16sampler2D sampler_,vec3 P,float lod);
f16vec4 textureProjLod(f16sampler2D sampler_,f16vec3 P,float16_t lod);
f16vec4 textureProjLod(f16sampler2D sampler_,vec4 P,float lod);
f16vec4 textureProjLod(f16sampler2D sampler_,f16vec4 P,float16_t lod);
f16vec4 textureProjLod(f16sampler3D sampler_,vec4 P,float lod);
f16vec4 textureProjLod(f16sampler3D sampler_,f16vec4 P,float16_t lod);
float16_t textureProjLod(f16sampler1DShadow sampler_,vec4 P,float lod);
float16_t textureProjLod(f16sampler1DShadow sampler_,f16vec3 P,float lod,float16_t);
float16_t textureProjLod(f16sampler2DShadow sampler_,vec4 P,float lod);
float16_t textureProjLod(f16sampler2DShadow sampler_,f16vec3 P,float lod,float16_t);
f16vec4 textureProjLodOffset(f16sampler1D sampler_,vec2 P,float lod,int offset);
f16vec4 textureProjLodOffset(f16sampler1D sampler_,f16vec2 P,float16_t lod,int offset);
f16vec4 textureProjLodOffset(f16sampler1D sampler_,vec4 P,float lod,int offset);
f16vec4 textureProjLodOffset(f16sampler1D sampler_,f16vec4 P,float16_t lod,int offset);
f16vec4 textureProjLodOffset(f16sampler2D sampler_,vec3 P,float lod,ivec2 offset);
f16vec4 textureProjLodOffset(f16sampler2D sampler_,f16vec3 P,float16_t lod,ivec2 offset);
f16vec4 textureProjLodOffset(f16sampler2D sampler_,vec4 P,float lod,ivec2 offset);
f16vec4 textureProjLodOffset(f16sampler2D sampler_,f16vec4 P,float16_t lod,ivec2 offset);
f16vec4 textureProjLodOffset(f16sampler3D sampler_,vec4 P,float lod,ivec3 offset);
f16vec4 textureProjLodOffset(f16sampler3D sampler_,f16vec4 P,float16_t lod,ivec3 offset);
float16_t textureProjLodOffset(f16sampler1DShadow sampler_,vec4 P,float lod,int offset);
float16_t textureProjLodOffset(f16sampler1DShadow sampler_,f16vec3 P,float lod,float16_t offset,int);
float16_t textureProjLodOffset(f16sampler2DShadow sampler_,vec4 P,float lod,ivec2 offset);
float16_t textureProjLodOffset(f16sampler2DShadow sampler_,f16vec3 P,float lod,float16_t offset,ivec2);
f16vec4 textureGrad(f16sampler1D sampler_,float P,float dPdx,float dPdy);
f16vec4 textureGrad(f16sampler1D sampler_,float16_t P,float16_t dPdx,float16_t dPdy);
f16vec4 textureGrad(f16sampler2D sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
f16vec4 textureGrad(f16sampler2D sampler_,f16vec2 P,f16vec2 dPdx,f16vec2 dPdy);
f16vec4 textureGrad(f16sampler3D sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
f16vec4 textureGrad(f16sampler3D sampler_,f16vec3 P,f16vec3 dPdx,f16vec3 dPdy);
f16vec4 textureGrad(f16samplerCube sampler_,vec3 P,vec3 dPdx,vec3 dPdy);
f16vec4 textureGrad(f16samplerCube sampler_,f16vec3 P,f16vec3 dPdx,f16vec3 dPdy);
f16vec4 textureGrad(f16sampler2DRect sampler_,vec2 P,vec2 dPdx,vec2 dPdy);
f16vec4 textureGrad(f16sampler2DRect sampler_,f16vec2 P,f16vec2 dPdx,f16vec2 dPdy);
f16vec4 textureGrad(f16sampler1DArray sampler_,vec2 P,float dPdx,float dPdy);
f16vec4 textureGrad(f16sampler1DArray sampler_,f16vec2 P,float16_t dPdx,float16_t dPdy);
f16vec4 textureGrad(f16sampler2DArray sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
f16vec4 textureGrad(f16sampler2DArray sampler_,f16vec3 P,f16vec2 dPdx,f16vec2 dPdy);
f16vec4 textureGrad(f16samplerCubeArray sampler_,vec4 P,vec3 dPdx,vec3 dPdy);
f16vec4 textureGrad(f16samplerCubeArray sampler_,f16vec4 P,f16vec3 dPdx,f16vec3 dPdy);
float16_t textureGrad(f16sampler1DShadow sampler_,vec3 P,float dPdx,float dPdy);
float16_t textureGrad(f16sampler2DShadow sampler_,vec3 P,vec2 dPdx,vec2 dPdy);
float16_t textureGrad(f16sampler1DShadow,f16vec2,float,float16_t,float16_t);
float16_t textureGrad(f16sampler2DShadow,f16vec2,float,f16vec2,f16vec2);
float16_t textureGrad(f16samplerCubeShadow,vec4,vec3,vec3);
float16_t textureGrad(f16samplerCubeShadow,f16vec3,float,f16vec3,f16vec3);
float16_t textureGrad(f16sampler2DRectShadow,vec3,vec2,vec2);
float16_t textureGrad(f16sampler2DRectShadow,f16vec2,float,f16vec2,f16vec2);
float16_t textureGrad(f16sampler1DArrayShadow,vec3,float,float);
float16_t textureGrad(f16sampler1DArrayShadow,f16vec2,float,float16_t,float16_t);
float16_t textureGrad(f16sampler2DArrayShadow,vec4,vec2,vec2);
float16_t textureGrad(f16sampler2DArrayShadow,f16vec3,float,f16vec2,f16vec2);
float16_t textureGrad(f16samplerCubeArrayShadow,vec4,float,vec3,vec3);
float16_t textureGrad(f16samplerCubeArrayShadow,f16vec4,float,f16vec3,f16vec3);
f16vec4 textureGradOffset(f16sampler1D,float,float,float,int);
f16vec4 textureGradOffset(f16sampler1D,float16_t,float16_t,float16_t,int);
f16vec4 textureGradOffset(f16sampler2D,vec2,vec2,vec2,ivec2);
f16vec4 textureGradOffset(f16sampler2D,f16vec2,f16vec2,f16vec2,ivec2);
f16vec4 textureGradOffset(f16sampler3D,vec3,vec3,vec3,ivec3);
f16vec4 textureGradOffset(f16sampler3D,f16vec3,f16vec3,f16vec3,ivec3);
f16vec4 textureGradOffset(f16sampler2DRect,vec2,vec2,vec2,ivec2);
f16vec4 textureGradOffset(f16sampler2DRect,f16vec2,f16vec2,f16vec2,ivec2);
f16vec4 textureGradOffset(f16sampler1DArray,vec2,float,float,int);
f16vec4 textureGradOffset(f16sampler1DArray,f16vec2,float16_t,float16_t,int);
f16vec4 textureGradOffset(f16sampler2DArray,vec3,vec2,vec2,ivec2);
f16vec4 textureGradOffset(f16sampler2DArray,f16vec3,f16vec2,f16vec2,ivec2);
float16_t textureGradOffset(f16sampler1DShadow,vec3,float,float,int);
float16_t textureGradOffset(f16sampler1DShadow,f16vec2,float,float16_t,float16_t,int);
float16_t textureGradOffset(f16sampler2DShadow,vec3,vec2,vec2,ivec2);
float16_t textureGradOffset(f16sampler2DShadow,f16vec2,float,f16vec2,f16vec2,ivec2);
float16_t textureGradOffset(f16sampler2DRectShadow,vec3,vec2,vec2,ivec2);
float16_t textureGradOffset(f16sampler2DRectShadow,f16vec2,float,f16vec2,f16vec2,ivec2);
float16_t textureGradOffset(f16sampler1DArrayShadow,vec3,float,float,int);
float16_t textureGradOffset(f16sampler1DArrayShadow,f16vec2,float,float16_t,float16_t,int);
float16_t textureGradOffset(f16sampler2DArrayShadow,vec4,vec2,vec2,ivec2);
float16_t textureGradOffset(f16sampler2DArrayShadow,f16vec3,float,f16vec2,f16vec2,ivec2);
f16vec4 textureProjGrad(f16sampler1D,vec2,float,float);
f16vec4 textureProjGrad(f16sampler1D,f16vec2,float16_t,float16_t);
f16vec4 textureProjGrad(f16sampler1D,vec4,float,float);
f16vec4 textureProjGrad(f16sampler1D,f16vec4,float16_t,float16_t);
f16vec4 textureProjGrad(f16sampler2D,vec3,vec2,vec2);
f16vec4 textureProjGrad(f16sampler2D,f16vec3,f16vec2,f16vec2);
f16vec4 textureProjGrad(f16sampler2D,vec4,vec2,vec2);
f16vec4 textureProjGrad(f16sampler2D,f16vec4,f16vec2,f16vec2);
f16vec4 textureProjGrad(f16sampler3D,vec4,vec3,vec3);
f16vec4 textureProjGrad(f16sampler3D,f16vec4,f16vec3,f16vec3);
f16vec4 textureProjGrad(f16sampler2DRect,vec3,vec2,vec2);
f16vec4 textureProjGrad(f16sampler2DRect,f16vec3,f16vec2,f16vec2);
f16vec4 textureProjGrad(f16sampler2DRect,vec4,vec2,vec2);
f16vec4 textureProjGrad(f16sampler2DRect,f16vec4,f16vec2,f16vec2);
float16_t textureProjGrad(f16sampler1DShadow,vec4,float,float);
float16_t textureProjGrad(f16sampler1DShadow,f16vec3,float,float16_t,float16_t);
float16_t textureProjGrad(f16sampler2DShadow,vec4,vec2,vec2);
float16_t textureProjGrad(f16sampler2DShadow,f16vec3,float,f16vec2,f16vec2);
float16_t textureProjGrad(f16sampler2DRectShadow,vec4,vec2,vec2);
float16_t textureProjGrad(f16sampler2DRectShadow,f16vec3,float,f16vec2,f16vec2);
f16vec4 textureProjGradOffset(f16sampler1D,vec2,float,float,int);
f16vec4 textureProjGradOffset(f16sampler1D,f16vec2,float16_t,float16_t,int);
f16vec4 textureProjGradOffset(f16sampler1D,vec4,float,float,int);
f16vec4 textureProjGradOffset(f16sampler1D,f16vec4,float16_t,float16_t,int);
f16vec4 textureProjGradOffset(f16sampler2D,vec3,vec2,vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2D,f16vec3,f16vec2,f16vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2D,vec4,vec2,vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2D,f16vec4,f16vec2,f16vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler3D,vec4,vec3,vec3,ivec3);
f16vec4 textureProjGradOffset(f16sampler3D,f16vec4,f16vec3,f16vec3,ivec3);
f16vec4 textureProjGradOffset(f16sampler2DRect,vec3,vec2,vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2DRect,f16vec3,f16vec2,f16vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2DRect,vec4,vec2,vec2,ivec2);
f16vec4 textureProjGradOffset(f16sampler2DRect,f16vec4,f16vec2,f16vec2,ivec2);
float16_t textureProjGradOffset(f16sampler1DShadow,vec4,float,float,int);
float16_t textureProjGradOffset(f16sampler1DShadow,f16vec3,float,float16_t,float16_t,int);
float16_t textureProjGradOffset(f16sampler2DShadow,vec4,vec2,vec2,ivec2);
float16_t textureProjGradOffset(f16sampler2DShadow,f16vec3,float,f16vec2,f16vec2,ivec2);
float16_t textureProjGradOffset(f16sampler2DRectShadow,vec4,vec2,vec2,ivec2);
float16_t textureProjGradOffset(f16sampler2DRectShadow,f16vec3,float,f16vec2,f16vec2,ivec2);

#endif